name: Flux Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  kustomize-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Build kustomize manifests
        run: |
          flux build kustomization ./demo
