name: Flux Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  kustomize-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Flux CLI
        run: |
          curl -s https://fluxcd.io/install.sh | sudo bash
          sudo mv flux /usr/local/bin/fluxctl
